---

install:
  - SET PATH=C:\ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:/Windows/system32

  - ps: |
      if ($env:ruby_version -like "*head*") {
        $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-$env:ruby_version.exe", "$pwd/ruby-setup.exe")
        cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby$env:ruby_version
      }

  - git clone -q --depth=5  --no-tags --branch=byebug https://github.com/MSP-greg/rb-readline.git C:\rb-readline

  - set n_dir=C:\ruby%ruby_version%\lib\ruby\site_ruby\%ruby_abi_version%
  - attrib.exe -r %n_dir%\*.rb
  - del /q %n_dir%\readline.rb
  - del /q %n_dir%\rbreadline.rb
  - copy C:\rb-readline\lib\readline.rb %n_dir%\readline.rb
  - copy C:\rb-readline\lib\rbreadline.rb %n_dir%\rbreadline.rb

  - echo %PATH%

  - ruby --version
  - where ruby

  - gem --version
  - where gem

  - gem install bundler -v 1.16.1 --no-document --force --conservative
  - bundle config force_ruby_platform true
  - bundle install --jobs 3 --retry 3 --path .bundle/gems

build_script:
  - bundle exec rake clobber compile

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "23"
      ruby_abi_version: 2.3.0
    - ruby_version: 23-x64
      ruby_abi_version: 2.3.0
    - ruby_version: "24"
      ruby_abi_version: 2.4.0
    - ruby_version: 24-x64
      ruby_abi_version: 2.4.0
    - ruby_version: "25"
      ruby_abi_version: 2.5.0
    - ruby_version: 25-x64
      ruby_abi_version: 2.5.0
    - ruby_version: head-x86
      ruby_abi_version: 2.6.0
    - ruby_version: head-x64
      ruby_abi_version: 2.6.0

cache:
  - .bundle/gems

matrix:
  allow_failures:
    - ruby_version: head
    - ruby_version: head-x64

branches:
  only:
    - master

notifications:
  - provider: Email

    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
