---
init:
  # clean path up to just what we need
  - set PATH=C:\ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Windows\system32;C:\Windows
  # Loads trunk build, updates MSYS2 / MinGW to most recent gcc compiler, replaces GDBM & OpenSSL packages
  - if %ruby_version%==_trunk (
      appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:\ruby_trunk.7z &
      7z x C:\ruby_trunk.7z -oC:\ruby_trunk & C:\ruby_trunk\trunk_msys2.cmd)

version: "{build}"

install:
  - echo %PATH%

  - ruby --version
  - where ruby

  - gem --version
  - where gem

  - gem install bundler -v 1.16.1 --no-document --force --conservative
  - bundle config force_ruby_platform true
  - bundle install --jobs 3 --retry 3 --path .bundle/gems/%ruby_version%

build_script:
  - bundle exec rake clobber
  - bundle exec rake compile

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: 22-x64
    - ruby_version: '23'
    - ruby_version: 23-x64
    - ruby_version: '24'
    - ruby_version: 24-x64
    - ruby_version: _trunk

  codeclimate_repo_token: '02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408'

cache:
  - .bundle/gems

matrix:
  fast_finish: true
  allow_failures:
    - ruby_version: _trunk

branches:
  only:
    - master

notifications:
  - provider: Email

    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
